### add node1
POST http://localhost:8100/addNode
Content-Type: application/json

{
    "instanceId": "instance1", 
    "nodeId": "node123", 
    "url": "http://127.0.0.1:8000",
    "role": 0, 
    "status": 1
}


### add node2
POST http://localhost:8100/addNode
Content-Type: application/json

{
    "instanceId": "instance1",
    "nodeId": "node124",
    "url": "http://127.0.0.1:8000",
    "role": 0,
    "status": 1
}


### 更新分区信息
POST http://localhost:8100/updatePartitionConfig
Content-Type: application/json

{
    "instanceId": "instance1",
    "partitionKey": "id",
    "numberOfPartitions": 2,
    "partitions": [
        {"partitionId": 0, "nodeId": "node123"},
        {"partitionId": 1, "nodeId": "node124"}
    ]
}

### 获取分区信息
GET http://localhost:8100/getPartitionConfig?instanceId=instance1



### 更新分区信息：
POST http://localhost:8100/updatePartitionConfig
Content-Type: application/json

{
    "instanceId": "instance1",
    "partitionKey": "id",
    "numberOfPartitions": 1,
    "partitions": [
        {"partitionId": 0, "nodeId": "node123"},
        {"partitionId": 0, "nodeId": "node124"}
    ]
}


### 查看instance下的所有node信息
GET http://localhost:8100/getInstance?instanceId=instance1
Content-Type: application/json

### 查看node信息
GET http://localhost:8100/getNodeInfo?instanceId=instance1&nodeId=node123
Content-Type: application/json

###
GET http://localhost:8100/getNodeInfo?instanceId=instance1&nodeId=node124
Content-Type: application/json


### 删除node信息
DELETE http://localhost:8100/removeNode?instanceId=instance1&nodeId=node123
Content-Type: application/json

### 删除node信息
DELETE http://localhost:8100/removeNode?instanceId=instance1&nodeId=node124
Content-Type: application/json